### ISSUE TITLE
framework not found JRMemory

### ISSUE THREAD

**Issue by LinhCute2002** [zesttbz/Project-FPS-Dylib#1]
cho mình hỏi sao lại bị lỗi này khi make ạ
![image](https://github.com/zesttbz/Project-FPS-Dylib/assets/138930983/0ebaad75-b3cf-4ab2-aba4-51da56aa62de)

**Comment by pubgiossss11** [comment]
cho hỏi bạn fix dc chưa tui cũng bị lỗi này :((

**Comment by zesttbz** [comment]
> cho hỏi bạn fix dc chưa tui cũng bị lỗi này :((

ib facebook mình fix nhé

**Comment by pubgiossss11** [comment]
> nhé

fb a là gì á

**Comment by zesttbz** [comment]
> > nhé
> 
> fb a là gì á
https://www.facebook.com/zest.tbz?mibextid=JRoKGi

**Comment by pubgiossss11** [comment]
k nt dc :((

Vào Th 4, 31 thg 1, 2024 lúc 12:10 Trần Hà Duy Anh ***@***.***>
đã viết:

**Comment by zesttbz** [comment]
> k nt dc :(( Vào Th 4, 31 thg 1, 2024 lúc 12:10 Trần Hà Duy Anh ***@***.***> đã viết:
> […](#)

mình acp r đấy

**Comment by hieukka** [comment]
fix lỗi này kiểu gì vậy anh em

**Comment by zesttbz** [comment]
> fix lỗi này kiểu gì vậy anh em

ib fb: https://facebook.com/zest.tbz
